### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by buhman** [buhman/elm-ui-test#1]
MVP:

- [x] use es7 async functions instead of promise ridiculousness
- [ ] `File.Ports` probably doesn't belong in `File` anymore
- [ ] separate `Text.HistoryCard` from `Text`, and re-use it in `File`
- [ ] actually implement a few option buttons (at least private)
- [x] send filename in file/multipart requests; verify default mimetype

Maybe:

- [ ] add port and `HistoryCard` button for copy
  - https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript/30810322#30810322
  - https://github.com/JEG2/elm_clipboard_test/commits/master
- [ ] consider using inputs instead of text elements for history value display

Pre-image:

 - [ ] add html progress bar (hard/ugly because we're using two different http apis at the same time)
